# This workflow will install Python dependencies, run tests, run migration, check migration and lint with a back
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.4"
    - name: Install dependencies
      run: |
        make install
    - name: Lint with black
      run: |
        make format
    - name: Test with pytest-django
      run: |
        make test
    - name: make migrations
      run: |
        make check  
    - name: push migration
      run: |
        make check  
    - name: check migration
      run: |
        make check   
