# Generated by Django 5.1.1 on 2024-09-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="XmlDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xml_file", models.FileField(upload_to="xml_files/")),
                ("uploaded_xmlfile_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
