# Generated by Django 5.1.1 on 2024-09-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_xmldocument"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="content_doc",
            new_name="content_document",
        ),
    ]
