# Generated by Django 5.1.1 on 2024-09-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_rename_content_doc_content_content_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xmldocument",
            name="uploaded_xmlfile_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
